#commands for running large sets of pairwise fishers exact tests

#get mutation data in the format such as generated by subtyping.r script

#[,1]     [,2]      [,3]    [,4]    [,5]        [,19]
# SampleN Diagnosis Gene 1  Gene 2  Gene 3  ... Gene 17
# 1234    RARS      0       0       1       ... 0
# 1235    RA        1       0       0       ... 0
# ...

# Or

#[,1]     [,2]      [,3]    [,4]    [,5]        [,19]
# SampleN Diagnosis Gene 1  Gene 2  Gene 3  ... Gene 17
# 1234    RARS      No      No      Yes     ... No
# 1235    RA        Yes     No      No      ... No
# ...

comut.df <- dataframe(comut_data.tsv)

dumpmat <- matrix(0,ncol = 3); colnames(dumpmat) <- c("Comparison","pval","OR")
dumpmat <- dumpmat[-1,]
for (i in seq(3,19)) {
     for (j in seq(3,19)) {
         Tab<-table(comut.df[,i],comut.df[,j]);
         fish<-fisher.test(Tab);
         fishnames<-paste(colnames(comut.df[i]),(colnames(comut.df[j])));
         fishpval <- fish$p.value;
         fishOR <- fish[["estimate"]][["odds ratio"]];
         dumpmat <- rbind(dumpmat, c(fishnames, fishpval, fishOR))
     }
 }
write.table(dumpmat,"Papaem_Fish.tsv",sep="\t")

#This will generate 289 (17 x 17) contingency tables

dumpmat <- matrix(0,ncol = 3); colnames(dumpmat) <- c("Comparison","pval","OR")
dumpmat <- dumpmat[-1,]
for (i in seq(from = 8,to = 57)) {
     for (j in seq(from = 8,to = 57)) {
         Tab<-table(COSMIC_comut[,i],COSMIC_comut[,j]);
         fish<-fisher.test(Tab);
         fishnames<-paste(colnames(COSMIC_comut[i]),(colnames(COSMIC_comut[j])));
         fishpval <- fish$p.value;
         fishOR <- fish[["estimate"]][["odds ratio"]];
         dumpmat <- rbind(dumpmat, c(fishnames, fishpval, fishOR))
     }
 }
write.table(dumpmat,"COSMIC_Fish.txt",sep="\t",row.names=FALSE)
